<?php if ($block->shouldRenderQuantity()) :?>
    <div class="field qty">
        <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
        <div class="control">
            <input type="number"
                   name="qty"
                   id="qty"
                   min="0"
                   value="<?= $block->getProductDefaultQty() * 1 ?>"
                   title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                   class="input-text qty"
                   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
            />
        </div>
    </div>
<?php endif; ?>
